---
title: "fft.Rmd"
author: "Alicia Key"
date: "2022-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(dplyr)
library(ggplot2)
```

## Set a theme

```{r}
theme_set(theme_linedraw(base_size = 15))
```

## Functions for generating waveforms

```{r}
generate_waveform <- function(freq_hzs, amplitudes, decay_tau = NA, duration_s = 1.0, sr = 200) {
  t_samples <- seq(sr * duration_s)
  waveform_matrix = matrix(nrow = length(freq_hzs), ncol = length(t_samples))
  
  for (i in seq_along(freq_hzs)) {
    if (is.na(decay_tau)) {
      waveform_matrix[i, ] <- amplitudes[i] * cos(2 * pi * freq_hzs[i] * t_samples / sr)
    }
    else {
      waveform_matrix[i, ] <- amplitudes[i] * cos(2 * pi * freq_hzs[i] * t_samples / sr) * exp(-t_samples / (decay_tau * sr))
    }
  }
  
  wv <- colSums(waveform_matrix)
  
  data.frame(
    t_samples = t_samples,
    waveform = wv,
    waveform_norm = wv / length(wv)
  )
}
```

## Generate a more complex waveform

```{r}
waveform_2 <- generate_waveform(c(4.0), c(1.0))

waveform_2  %>%
  ggplot(aes(x = t_samples, y = waveform_norm)) +
    geom_line()
```

```{r}
# y <- fft(waveform_2$waveform / length(waveform_2$waveform))
# y[which(Re(y) > 0.05 | Im(y) > 0.05)]
```

```{r}
fft_df <- function(waveform_df) {
  y <- fft(waveform_df$waveform_norm)
  
  data.frame(
    fft_idx = seq_along(y),
    fft_complex = y,
    fft_re = Re(y),
    fft_im = Im(y),
    fft_mod = Mod(y)
  )
} 
```

Now make a plot of the FFT

```{r}
waveform_2 %>%
  fft_df() %>%
  ggplot(aes(x = fft_idx, y = fft_im)) +
  geom_line()
```
